### ISSUE TITLE
Embedding of Flask in a class structure

### ISSUE THREAD

**Issue by nquetschlich** [cda-tum/mqt-bench#189]
So far, Flask was implemented on the module level in `mqt/benchviewer/main.py`. However, to avoid any global variables, it should be embedded in the `Server` class. Therefore, [class-full views](https://flask.palletsprojects.com/en/2.2.x/views/) should be used.

**Comment by burgholzer** [comment]
Given that we plan to migrate away from flask in the future, I am going to close this issue as unplanned.
