### ISSUE TITLE
✨ Upgrading the qasm parser

### ISSUE THREAD

**Issue by nquetschlich** [cda-tum/mqt-bench#297]
### What's the problem this feature will solve?

Currently, `MQT Bench` uses the native qasm parser via [QuantumCircuit.from_qasm_file()](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#from_qasm_file) and `QuantumCircuit.qasm()`. However, in [Qiskit `v0.43.0`](https://docs.quantum.ibm.com/api/qiskit/release-notes/0.43), a more powerful qasm parser has been released: [qasm2](https://docs.quantum.ibm.com/api/qiskit/qasm2). 

### Describe the solution you'd like

Migration to `qasm2.loads(..)` and `qasm2.dumps(...)`.

**Comment by burgholzer** [comment]
To add to that: Dumping QASM via `qc.qasm()` is actually deprecated as off the most recent Qiskit version.
Loading from Qiskit has internally switched to the new Parser already in the latest version.
We should still use the new commands wherever possible 👍🏼 
In addition we might think about exporting to OpenQASM3 as it is getting more wide-spread support (also within our own toolkit).
