### ISSUE TITLE
Run on local or remote simulator such like IBM

### ISSUE THREAD

**Issue by dangokuson** [cda-tum/mqt-bench#345]
Hi There~

I want to ask how can I run the benchmark circuit and visualize the result by using these benchmark sample scripts provided by MQT Bench on the local or remote simulator?

Thanks

**Comment by nquetschlich** [comment]
Hi @dangokuson, thanks a lot for reaching out. The purpose of MQT Bench is to provide quantum circuits that one can use to evaluate software tools or to execute the circuits on either a simulator/quantum computer. 

For the actual execution, we recommend to use the simulator/device of your choice. The easiest way would probably to use Qiskit for that.
